language: c
sudo: required
service: docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: cp lib/mock.ml lib/nvml.ml
script: rm stubs/nvml_stubs.c && touch stubs/nvml_stubs.c
script: bash -ex .travis-docker.sh
env:
  global:
    - PACKAGE=gpumon
    - PINS="gpumon:."
    - BASE_REMOTE="https://github.com/xapi-project/xs-opam.git"
  matrix:
    - DISTRO="debian-9-ocaml-4.06"
